fitness_institucion:
    resource: "@FitnessBundle/Controller/InstitucionController.php"
    type:     annotation

fitness:
    resource: "@FitnessBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
usuarios:
    resource: "@UsuariosBundle/Resources/config/routing.yml"
    prefix:   admin/
